minimum_pre_commit_version: 1.21.0
repos:
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes

# format Python code with black
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
      #      language_version: python3.7

  ## check docstrings
  #- repo: https://github.com/PyCQA/pydocstyle
  #  rev: 5.0.2
  #  hooks:
  #  - id: pydocstyle
  #    args: ["--ignore=D10,D21,D202"]
  #

# bandit
-   repo: https://github.com/PyCQA/bandit
    rev: '1.6.2'
    hooks:
    - id: bandit
      args: ["-c", ".bandit"]

# static type checking with mypy
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
  hooks:
  - id: mypy

# flake8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
      additional_dependencies: ["flake8-bugbear"]
      args: [--max-line-length=120]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
  - id: check-added-large-files
  - id: check-docstring-first
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-ast
  - id: check-builtin-literals
  - id: detect-private-key
  - id: mixed-line-ending
